name: Playwright Test and Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests
        run: npx playwright test --reporter=junit,html
      - name: Upload JUnit Test Results (output.xml)
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-results
          path: output.xml
          retention-days: 7
      - name: Upload HTML Test Report (results.html)
        uses: actions/upload-artifact@v3
        with:
          name: playwright-html-report
          path: test-results/index.html
          retention-days: 7

  deploy_to_staging:
    runs-on: ubuntu-latest
    needs: test  # Runs after the 'test' job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy to Staging Environment
        run: ./deploy-to-staging.sh

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: deploy_to_staging  # Runs after the 'deploy_to_staging' job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy to Production
        run: ./deploy-to-production.sh
